name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Create a release.
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release Text
        run: echo ${{ github.sha }} > Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          generate_release_notes: true
          files: |
            Release.txt
            LICENSE
            README.md
          prerelease: contains(github.ref, '-')

